// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import streadwayamqp "github.com/streadway/amqp"

// AmqpClient is an autogenerated mock type for the AmqpClient type
type AmqpClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *AmqpClient) Close() {
	_m.Called()
}

// Connect provides a mock function with given fields:
func (_m *AmqpClient) Connect() (*streadwayamqp.Channel, error) {
	ret := _m.Called()

	var r0 *streadwayamqp.Channel
	if rf, ok := ret.Get(0).(func() *streadwayamqp.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*streadwayamqp.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
