# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: amqp
  profiles:
    include:
    - amqp

amqp:
  host: rabbitmq
  port: 5672
  username: user
  password: password

logging:
  level: debug
